/* Pillar page directory data — San Antonio.
 *
 * Real listings from Kelvin's filtered directory, data-audited July 2026:
 *   · Category mismatches corrected (see AUDIT notes on individual entries).
 *   · National chains excluded pending owner verification: Burger King,
 *     Black Rifle Coffee Company, TA Travel Center, The UPS Store.
 *   · Duplicate ticker symbols de-conflicted: House of RoyalT HOUS→ROYA,
 *     Hair By Michael Farris HAIR→FARR, Black Contractors Assn BLAC→BCAS,
 *     J'Jireh's J'JI→JJIR (alphanumeric only).
 *   · Tracking parameters and redirect wrappers stripped from URLs; one
 *     spam-directory link dropped (Preferred Natural Hair Braiding).
 *   · Emails intentionally omitted from the public page (harvest risk);
 *     phone + website only.
 *
 * `verified` is false for every entry: these are curated seed listings, not
 * yet owner-claimed or KIN-verified (DISCOVERY_BLUEPRINT.md §2.3). The gold
 * badge appears as businesses complete verification.
 *
 * `featured: true` gives an entry priority placement + the Featured chip.
 */

export const PLACEHOLDER_LISTINGS = false;

export const LAST_UPDATED = "July 2026";

export const WAITLIST_URL = "https://thekinapp.carrd.co/";

export const CATEGORIES = [
  {
    id: "restaurants",
    title: "Restaurants & Food",
    blurb:
      "From soul food Sundays to jerk chicken and pan dulce — kitchens owned by your neighbors.",
  },
  {
    id: "beauty",
    title: "Beauty, Hair & Wellness",
    blurb: "Braiders, stylists, locticians, and spas where the culture is the craft.",
  },
  {
    id: "retail",
    title: "Retail & Shopping",
    blurb: "Shops and boutiques with stories you won't find at the mall.",
  },
  {
    id: "services",
    title: "Professional & Home Services",
    blurb:
      "Builders, consultants, security, tech, and the businesses that keep the city running.",
  },
  {
    id: "community",
    title: "Community & Organizations",
    blurb:
      "The institutions documenting, connecting, and championing Black business in San Antonio.",
  },
];

export const LISTINGS = [
  /* ---------------------------- Restaurants & Food --------------------- */
  {
    category: "restaurants",
    name: "The Cajun Coffee Shack",
    ticker: "CAJU",
    neighborhood: "Far West Side",
    city: "San Antonio",
    phone: "",
    description: "Cajun-inspired coffee shack on Potranco Road.",
    verified: false,
    featured: false,
    website: "https://cajuncoffeeshack.toast.site/",
  },
  {
    category: "restaurants",
    name: "The Jerk Shack",
    ticker: "JERK",
    neighborhood: "West Side",
    city: "San Antonio",
    phone: "2107767780",
    description:
      "Humble window-serve for jerk chicken, patties & curries, plus veggie options & meat by the pound.",
    verified: false,
    featured: false,
    website: "http://www.thejerkshacksatx.com/",
  },
  {
    // AUDIT: was "Clothing store" — it's a custom cookie bakery.
    category: "restaurants",
    name: "House of Cookie Couture",
    ticker: "HOUS",
    neighborhood: "West Side",
    city: "San Antonio",
    phone: "2109826518",
    description: "Custom cookies and baked treats on Potranco Road.",
    verified: false,
    featured: false,
    website: "http://www.houseofcookiecouture.com/",
  },
  {
    category: "restaurants",
    name: "Ubuntu Cuisine",
    ticker: "UBUN",
    neighborhood: "Northwest Side",
    city: "San Antonio",
    phone: "2108886161",
    description:
      "Traditional African meat pies, rice dishes & soups prepared in a modest strip-mall storefront.",
    verified: false,
    featured: false,
    website: "https://ubuntucuisine.com/",
  },
  {
    category: "restaurants",
    name: "Trices Cafe and Lounge",
    ticker: "TRIC",
    neighborhood: "Northwest Side",
    city: "San Antonio",
    phone: "2108067770",
    description: "Neighborhood cafe and lounge on Eckhert Road.",
    verified: false,
    featured: false,
    website: "https://tricesrestaurant.square.site/",
  },
  {
    category: "restaurants",
    name: "Fuel F33D The Health Shack",
    ticker: "FUEL",
    neighborhood: "Medical Center",
    city: "San Antonio",
    phone: "2104138092",
    description: "Health-focused eats near the Medical Center.",
    verified: false,
    featured: false,
    website: "http://www.fuelf33dhealthshack.com/",
  },
  {
    category: "restaurants",
    name: "Panifico Bake Shop",
    ticker: "PANI",
    neighborhood: "Near West Side",
    city: "San Antonio",
    phone: "2104349290",
    description:
      "Cheerful bakery specializing in custom cakes & pan dulce, plus other treats baked daily.",
    verified: false,
    featured: false,
    website: "https://www.panifico.com/",
  },
  {
    category: "restaurants",
    name: "Nome's Catering and Event Planning Services",
    ticker: "NOME",
    neighborhood: "North Central",
    city: "San Antonio",
    phone: "2105702035",
    description: "Full-service catering and event planning on West Avenue.",
    verified: false,
    featured: false,
    website: "https://nomecateringsa.com/",
  },
  {
    category: "restaurants",
    name: "Tony G's Soul Food",
    ticker: "TONY",
    neighborhood: "East Side",
    city: "San Antonio",
    phone: "2104511234",
    description:
      "Bright option for down-home Southern-style breakfasts & lunches, plus Sunday brunch & live jazz.",
    verified: false,
    featured: false,
    website: "http://www.tonygssoulfood.com/",
  },
  {
    category: "restaurants",
    name: "Momma Luv's Soul & Caribbean Food",
    ticker: "MOMM",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2109770060",
    description: "Soul food and Caribbean plates on Austin Highway.",
    verified: false,
    featured: false,
    website: "https://online.skytab.com/s/mommaluvssoul",
  },
  {
    // AUDIT: was "Food producer" — it's a mobile food trailer.
    category: "restaurants",
    name: "MD305 Soulfood Catfish & Wings",
    ticker: "MD30",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "",
    description: "Soul food, catfish & wings from a mobile food trailer.",
    verified: false,
    featured: false,
    website: "http://www.md305.com/",
  },
  {
    category: "restaurants",
    name: "Meeks Cafe",
    ticker: "MEEK",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2104293158",
    description: "Takeout cafe on North Foster Road.",
    verified: false,
    featured: false,
    website: "https://www.meekscafe.com/",
  },
  {
    // AUDIT: was "Office Supplies Wholesaler" — it's a BBQ restaurant.
    category: "restaurants",
    name: "The Big Bib",
    ticker: "BIGB",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2106548400",
    description: "BBQ restaurant — dine in, carry out and catering.",
    verified: false,
    featured: false,
    website: "https://www.thebigbib.com",
  },

  /* ------------------------- Beauty, Hair & Wellness -------------------- */
  {
    category: "beauty",
    name: "The Art of Hair Studio",
    ticker: "ARTO",
    neighborhood: "West Side",
    city: "San Antonio",
    phone: "8303835151",
    description: "Hair studio on Culebra Road.",
    verified: false,
    featured: false,
    website: "http://bit.ly/artofhairstudio",
  },
  {
    category: "beauty",
    name: "Adjia's Hair Braiding",
    ticker: "ADJI",
    neighborhood: "West Side",
    city: "San Antonio",
    phone: "2108128121",
    description: "African hair braiding off SW Loop 410.",
    verified: false,
    featured: false,
    website: "https://adjiashairbraiding.zoca.com/",
  },
  {
    category: "beauty",
    name: "Anointed SkinKare",
    ticker: "ANOI",
    neighborhood: "West Side",
    city: "San Antonio",
    phone: "2104469544",
    description: "Facial spa and skincare studio on Culebra Road.",
    verified: false,
    featured: false,
    website: "https://anointedskinkare.glossgenius.com/",
  },
  {
    category: "beauty",
    name: "Flo T African Hair Braiding",
    ticker: "FLOT",
    neighborhood: "West Side",
    city: "San Antonio",
    phone: "2109605344",
    description: "African hair braiding on Grissom Road.",
    verified: false,
    featured: false,
    website: "https://flotafricanhairbraiding.as.me/",
  },
  {
    category: "beauty",
    name: "Elizabeth's Hair Braiding & Locks",
    ticker: "ELIZ",
    neighborhood: "Northwest Side",
    city: "San Antonio",
    phone: "2106029053",
    description: "Braids and locks on Wurzbach Road.",
    verified: false,
    featured: false,
    website: "https://elizabethhairbraidingandlocks.godaddysites.com/",
  },
  {
    category: "beauty",
    name: "Flair 55 Hair Salon",
    ticker: "FLAI",
    neighborhood: "Far Northwest",
    city: "San Antonio",
    phone: "2105577100",
    description: "Full-service hair salon off I-10 West.",
    verified: false,
    featured: false,
    website: "https://www.flair55.com/",
  },
  {
    category: "beauty",
    name: "Stevihair Styles African Hair Braiding",
    ticker: "STEV",
    neighborhood: "Northwest Side",
    city: "San Antonio",
    phone: "2107125716",
    description: "African hair braiding and salon on NW Loop 410.",
    verified: false,
    featured: false,
    website: "",
  },
  {
    category: "beauty",
    name: "The Bandoo Salon & Spa",
    ticker: "BAND",
    neighborhood: "Northwest Side",
    city: "San Antonio",
    phone: "2109984247",
    description: "Salon and spa on Callaghan Road.",
    verified: false,
    featured: false,
    website: "https://www.thebandoosalonandspa.com/",
  },
  {
    // AUDIT: spam-directory link dropped from source data.
    category: "beauty",
    name: "Preferred Natural Hair Braiding",
    ticker: "PREF",
    neighborhood: "Medical Center",
    city: "San Antonio",
    phone: "2105645258",
    description: "Natural hair braiding on Babcock Road.",
    verified: false,
    featured: false,
    website: "",
  },
  {
    category: "beauty",
    name: "Unique Lenique's Beauty Spot",
    ticker: "UNIQ",
    neighborhood: "North Central",
    city: "San Antonio",
    phone: "5043855751",
    description: "Hair salon off NW Loop 410.",
    verified: false,
    featured: false,
    website: "http://www.ulbspot.com/",
  },
  {
    category: "beauty",
    name: "Studio 55 Luxe Beauty",
    ticker: "STUD",
    neighborhood: "North Central",
    city: "San Antonio",
    phone: "2102339427",
    description: "Luxe beauty studio on West Rector Drive.",
    verified: false,
    featured: false,
    website: "http://studio55luxebeauty.com/",
  },
  {
    category: "beauty",
    name: "Harmoni Salon",
    ticker: "HARM",
    neighborhood: "Alamo Heights area",
    city: "San Antonio",
    phone: "2104954920",
    description: "Hair salon on West Sunset Road.",
    verified: false,
    featured: false,
    website: "http://www.harmonisalons.com/",
  },
  {
    category: "beauty",
    name: "M Noire Beauty & Wellness",
    ticker: "MNOI",
    neighborhood: "North Side",
    city: "San Antonio",
    phone: "5304816643",
    description: "Beauty and wellness spa on Broadway.",
    verified: false,
    featured: false,
    website: "https://www.mnoirebeautywellness.com/",
  },
  {
    category: "beauty",
    name: "Goldie Loc's Natural Strands",
    ticker: "GOLD",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2108570446",
    description: "Loctician studio for natural strands.",
    verified: false,
    featured: false,
    website: "https://www.goldielocstx.com/",
  },
  {
    // AUDIT: ticker de-conflicted HOUS→ROYA (collision with House of
    // Cookie Couture).
    category: "beauty",
    name: "House of RoyalT Beauty Bar & Boutique",
    ticker: "ROYA",
    neighborhood: "East Side",
    city: "San Antonio",
    phone: "2103336001",
    description: "Beauty bar and boutique at Coca-Cola Place.",
    verified: false,
    featured: false,
    website: "https://www.thehouseofroyalt.com/",
  },
  {
    category: "beauty",
    name: "Mallorca Salon Studios & Suites",
    ticker: "MALL",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2106863210",
    description: "Salon studios and suites on Thousand Oaks Drive.",
    verified: false,
    featured: false,
    website: "https://mallorcasalonstudios.com/",
  },
  {
    category: "beauty",
    name: "La Belle African Hair Braiding",
    ticker: "LABE",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2109991777",
    description: "African hair braiding on Walzem Road.",
    verified: false,
    featured: false,
    website: "http://www.labelleafricanbraids.com/",
  },
  {
    // AUDIT: ticker de-conflicted HAIR→FARR (collision with Hair N Bulk).
    category: "beauty",
    name: "Hair By Michael Farris",
    ticker: "FARR",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2106891075",
    description: "Stylist studio on Walzem Road.",
    verified: false,
    featured: false,
    website: "http://www.facebook.com/thurstyroots",
  },
  {
    category: "beauty",
    name: "Divinity Massage & Oasis Spa",
    ticker: "DIVI",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2108840341",
    description: "Day spa and massage studio on Walzem Road.",
    verified: false,
    featured: false,
    website: "https://www.divinityoasis.com/",
  },
  {
    // AUDIT: ticker sanitized J'JI→JJIR (alphanumeric only).
    category: "beauty",
    name: "J'Jireh's Salon & Hair Restoration Center",
    ticker: "JJIR",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2106469200",
    description: "Salon and hair restoration center on Walzem Road.",
    verified: false,
    featured: false,
    website: "http://www.jjirehssalon.com/",
  },
  {
    category: "beauty",
    name: "Maven Hair Studio",
    ticker: "MAVE",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2105770163",
    description: "Beauty salon on Nacogdoches Road.",
    verified: false,
    featured: false,
    website: "http://www.mavenhairstudio.com/",
  },
  {
    category: "beauty",
    name: "Meticulous Hair Salon",
    ticker: "METI",
    neighborhood: "East Side",
    city: "San Antonio",
    phone: "2104786263",
    description: "Hair salon on South WW White Road.",
    verified: false,
    featured: false,
    website: "http://www.styleseat.com/monicaprice",
  },
  {
    category: "beauty",
    name: "Sublime Hair Salon",
    ticker: "SUBL",
    neighborhood: "Converse",
    city: "Converse",
    phone: "2109948199",
    description: "Beauty salon on Binz Engleman Road.",
    verified: false,
    featured: false,
    website: "",
  },
  {
    category: "beauty",
    name: "BraidGirl Beauty Salon",
    ticker: "BRAI",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2533748555",
    description: "Braiding salon on Knights Haven.",
    verified: false,
    featured: false,
    website: "https://sites.google.com/view/braidgirl/home",
  },
  {
    category: "beauty",
    name: "Goddess African Hair Braiding",
    ticker: "GODD",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2103100001",
    description: "African hair braiding near Walzem Road.",
    verified: false,
    featured: false,
    website: "http://goddessafricanhairbraiding.wordpress.com/",
  },
  {
    category: "beauty",
    name: "Lady B African Hair Braiding & Boutique",
    ticker: "LADY",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2106390671",
    description: "Braiding salon and boutique on Montgomery Drive.",
    verified: false,
    featured: false,
    website: "https://ladybhairboutique.com/",
  },
  {
    // AUDIT: tracking parameters stripped from URL.
    category: "beauty",
    name: "Virgo Hair Braiding Salon",
    ticker: "VIRG",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2105962909",
    description: "African braiding salon on Binz Engleman Road.",
    verified: false,
    featured: false,
    website: "https://virgohairbraiding.com/",
  },

  /* ----------------------------- Retail & Shopping ---------------------- */
  {
    category: "retail",
    name: "The Sunnah the Better Islamic Gift Shop",
    ticker: "SUNN",
    neighborhood: "Northwest Side",
    city: "San Antonio",
    phone: "2108880140",
    description:
      "Family-owned shop since 1993 selling traditional Islamic apparel in larger sizes, plus other gifts.",
    verified: false,
    featured: false,
    website: "https://www.thesunnahthebetter.com/",
  },
  {
    // AUDIT: Google-redirect wrapper unwrapped to the actual Facebook page.
    category: "retail",
    name: "NHP Wear",
    ticker: "NHPW",
    neighborhood: "Northwest Side",
    city: "San Antonio",
    phone: "2108838692",
    description: "Custom t-shirts and apparel on Fredericksburg Road.",
    verified: false,
    featured: false,
    website: "https://www.facebook.com/inhouseproductionz210/",
  },
  {
    category: "retail",
    name: "Hair N Bulk Beauty Supply",
    ticker: "HAIR",
    neighborhood: "Northwest Side",
    city: "San Antonio",
    phone: "2102017035",
    description: "Beauty supply store on Fredericksburg Road.",
    verified: false,
    featured: false,
    website: "https://hairnbulk.com/",
  },

  /* ----------------------- Professional & Home Services ----------------- */
  {
    category: "services",
    name: "MFAD Creative Group",
    ticker: "MFAD",
    neighborhood: "West Side",
    city: "San Antonio",
    phone: "2109607013",
    description: "Business management consulting on TX-151.",
    verified: false,
    featured: false,
    website: "http://www.management4aday.com/",
  },
  {
    category: "services",
    name: "The Bookkeeping Baddie",
    ticker: "BOOK",
    neighborhood: "West Side",
    city: "San Antonio",
    phone: "2108916064",
    description: "Bookkeeping services on Grissom Road.",
    verified: false,
    featured: false,
    website: "https://www.thebookkeepingbaddie.com/",
  },
  {
    category: "services",
    name: "The Picnic Basket Co.",
    ticker: "PICN",
    neighborhood: "Far West Side",
    city: "San Antonio",
    phone: "",
    description: "Curated picnic experiences and event planning.",
    verified: false,
    featured: false,
    website: "",
  },
  {
    category: "services",
    name: "Bez LLC",
    ticker: "BEZ",
    neighborhood: "North Central",
    city: "San Antonio",
    phone: "8002079868",
    description: "Business management consulting on Morocco Street.",
    verified: false,
    featured: false,
    website: "https://www.bezllc.com/",
  },
  {
    category: "services",
    name: "Greater Brands",
    ticker: "GREA",
    neighborhood: "North Side",
    city: "San Antonio",
    phone: "2105969005",
    description: "Brand-building consultancy on Naco Perrin Boulevard.",
    verified: false,
    featured: false,
    website: "http://www.buildgreaterbrands.com/",
  },
  {
    category: "services",
    name: "B Michele Branding Agency",
    ticker: "BMIC",
    neighborhood: "North Side",
    city: "San Antonio",
    phone: "8326376611",
    description: "Branding and business development agency on Perrin Beitel.",
    verified: false,
    featured: false,
    website: "https://bmichele.com/",
  },
  {
    category: "services",
    name: "Inflatable Movies & More",
    ticker: "INFL",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2108108511",
    description: "Outdoor movie-night rentals and event entertainment.",
    verified: false,
    featured: false,
    website: "",
  },
  {
    category: "services",
    name: "Nabulizis Alterations",
    ticker: "NABU",
    neighborhood: "West Side",
    city: "San Antonio",
    phone: "8176171359",
    description: "Custom tailoring and alterations.",
    verified: false,
    featured: false,
    website: "http://www.nabulizis.com/",
  },
  {
    category: "services",
    name: "Spirits Heart Childcare Center",
    ticker: "SPIR",
    neighborhood: "Converse",
    city: "Converse",
    phone: "2106087953",
    description: "In-home child day care services.",
    verified: false,
    featured: false,
    website: "",
  },
  {
    // AUDIT: was "Environmental Consulting Services" — it's guard & patrol
    // security.
    category: "services",
    name: "SMR Security Services",
    ticker: "SMRS",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2103934510",
    description: "Guard and patrol security services.",
    verified: false,
    featured: false,
    website: "",
  },
  {
    // AUDIT: was "Environmental Consulting Services" — it's tunneling
    // construction.
    category: "services",
    name: "Williams Tunneling Industries",
    ticker: "WILL",
    neighborhood: "North Side",
    city: "San Antonio",
    phone: "8328891468",
    description:
      "Service, easement, sewer and drainage tunnels, and shaft construction.",
    verified: false,
    featured: false,
    website: "https://www.wiltun.com",
  },
  {
    category: "services",
    name: "Wilson Consultants Alliance Group",
    ticker: "WILS",
    neighborhood: "Far North Side",
    city: "San Antonio",
    phone: "2106022368",
    description: "Administrative and general management consulting.",
    verified: false,
    featured: false,
    website: "",
  },
  {
    // AUDIT: was "Health Care Services" — author, training & promotional
    // products.
    category: "services",
    name: "Gwendolen Wilder, Author",
    ticker: "GWEN",
    neighborhood: "West Side",
    city: "San Antonio",
    phone: "2105197801",
    description:
      "Author of fiction and non-fiction, plus self-management and team-building training.",
    verified: false,
    featured: false,
    website: "https://www.gwendolenwilderauthor.com",
  },
  {
    // AUDIT: was "BBQ restaurant" — it's janitorial & detail cleaning.
    category: "services",
    name: "Smith's Sanitation Services",
    ticker: "SMIT",
    neighborhood: "Northeast Side",
    city: "San Antonio",
    phone: "2106874716",
    description:
      "Janitorial services, carpet and upholstery cleaning, and auto detailing.",
    verified: false,
    featured: false,
    website: "",
  },
  {
    // AUDIT: was "Health Care Services" — it's an architecture firm.
    // Source coordinates invalid (two longitudes) — excluded from map data.
    category: "services",
    name: "Sol Studio Architects",
    ticker: "SOLS",
    neighborhood: "Downtown",
    city: "San Antonio",
    phone: "2102408864",
    description: "Architectural services studio.",
    verified: false,
    featured: false,
    website: "http://www.solstudioarchitects.us",
  },
  {
    // AUDIT: was "Janitorial Services" — it's commercial construction.
    // Source coordinates invalid — excluded from map data.
    category: "services",
    name: "EJ Smith Construction Company",
    ticker: "EJSM",
    neighborhood: "East Side",
    city: "San Antonio",
    phone: "2102254601",
    description:
      "Commercial and institutional building, highway, bridge, and concrete construction.",
    verified: false,
    featured: false,
    website: "http://www.ejsmithind.com",
  },
  {
    // AUDIT: source coordinates invalid — excluded from map data.
    category: "services",
    name: "Sparkling Clean House Cleaning Source",
    ticker: "SPAR",
    neighborhood: "Far West Side",
    city: "San Antonio",
    phone: "2104206699",
    description:
      "House cleaning plus workshops teaching tools and systems for a clean, healthy home.",
    verified: false,
    featured: false,
    website: "",
  },
  {
    // AUDIT: was "Security Services" (guard/patrol) — it's IT &
    // cybersecurity.
    category: "services",
    name: "Digital Information Security Solutions",
    ticker: "DIGI",
    neighborhood: "North Side",
    city: "San Antonio",
    phone: "2109015895",
    description: "Custom programming and information-security services.",
    verified: false,
    featured: false,
    website: "https://www.digissllc.com",
  },
  {
    // AUDIT: malformed URL (http://https://) corrected.
    category: "services",
    name: "Rylet Industries",
    ticker: "RYLE",
    neighborhood: "Downtown",
    city: "San Antonio",
    phone: "8554795385",
    description: "Business consulting services.",
    verified: false,
    featured: false,
    website: "https://www.rylet.com",
  },
  {
    // AUDIT: was "Office Supplies Wholesaler" — it's IT professional
    // services.
    category: "services",
    name: "Techesive",
    ticker: "TECH",
    neighborhood: "Far West Side",
    city: "San Antonio",
    phone: "8006825850",
    description:
      "Enterprise application integration, software architecture, and secure records management.",
    verified: false,
    featured: false,
    website: "http://www.techesive.com",
  },

  /* ------------------------ Community & Organizations ------------------- */
  {
    category: "community",
    name: "San Antonio African American Community Archive and Museum (SAAACAM)",
    ticker: "SANA",
    neighborhood: "La Villita, Downtown",
    city: "San Antonio",
    phone: "2107243350",
    description:
      "Archive and museum preserving San Antonio's African American history at La Villita.",
    verified: false,
    featured: false,
    website: "http://saaacam.org/",
  },
  {
    category: "community",
    name: "Black Business San Antonio",
    ticker: "BLAC",
    neighborhood: "East Side",
    city: "San Antonio",
    phone: "",
    description: "Association championing Black-owned business across the city.",
    verified: false,
    featured: false,
    website: "",
  },
  {
    // AUDIT: ticker de-conflicted BLAC→BCAS (collision with Black Business
    // San Antonio).
    category: "community",
    name: "Black Contractors Association San Antonio",
    ticker: "BCAS",
    neighborhood: "East Side",
    city: "San Antonio",
    phone: "2109404501",
    description: "Business network for Black contractors and builders.",
    verified: false,
    featured: false,
    website: "https://blackcontractorsa.org/",
  },
  {
    category: "community",
    name: "African American Chamber of Commerce",
    ticker: "AFRI",
    neighborhood: "East Side",
    city: "San Antonio",
    phone: "2104359106",
    description: "Chamber of commerce serving San Antonio's Black business community.",
    verified: false,
    featured: false,
    website: "https://www.africanamericanchambersa.org/",
  },
];
